// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn3QYSffh9JLVo1M6v49s50bGWlpPwofY',
    appId: '1:529435792028:web:590fcc8d765fa6e1d01359',
    messagingSenderId: '529435792028',
    projectId: 'codeverse-all',
    authDomain: 'codeverse-all.firebaseapp.com',
    storageBucket: 'codeverse-all.appspot.com',
    measurementId: 'G-WESVRXE0HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYTjN58j3m3cx96Y9QjZltg8ZIiolV5Qo',
    appId: '1:529435792028:android:8e5bb8f2f14fe0ccd01359',
    messagingSenderId: '529435792028',
    projectId: 'codeverse-all',
    storageBucket: 'codeverse-all.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS9LS8oHOKocM3FtsCy2NiyvxEoOBvhSI',
    appId: '1:529435792028:ios:1afbd2548172441ed01359',
    messagingSenderId: '529435792028',
    projectId: 'codeverse-all',
    storageBucket: 'codeverse-all.appspot.com',
    iosClientId: '529435792028-0gs16hbladhbfbkhr6bpkdtm6ki8u2pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeverseUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS9LS8oHOKocM3FtsCy2NiyvxEoOBvhSI',
    appId: '1:529435792028:ios:1afbd2548172441ed01359',
    messagingSenderId: '529435792028',
    projectId: 'codeverse-all',
    storageBucket: 'codeverse-all.appspot.com',
    iosClientId: '529435792028-0gs16hbladhbfbkhr6bpkdtm6ki8u2pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeverseUser',
  );
}
